### ISSUE TITLE
Does flutter work on android TV?

### ISSUE THREAD

**Issue by kar** [coderJohnZhang/flutter_tv#1]
Hi John Zhang, I noticed you do a lot of Android TV stuff. I wanted to ask you, how is your experience in using flutter on Android TV currently? Is it usable? Thanks

**Comment by coderJohnZhang** [comment]
Yes, it can be used on Android TV. But it's hard to use so far, we must do many things that native android has already realized for us. So the tv app we developed by flutter can not be used for commercial purpose.
