### ISSUE TITLE
RawKeyboardListener

### ISSUE THREAD

**Issue by pierrederuel** [coderJohnZhang/flutter_tv#2]
Hi,

I found your your email address in your flitter GitHub project. I have a question about RawKeyboardListener. I have an external bluetooth barcode scanner and I want to receive the data without the need of selecting a TextField, do you think RawKeyboardListener is the right solution? I tried to use your solution but it doesn’t seem to work…

Thanks Pierre

**Comment by coderJohnZhang** [comment]
I think RawKeyboardListener can not solve your problem.
